---
- name: add repository key
  apt_key:
    id: "7BD9BF62"
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present
  tags:
    - nginx

- name: add repository url for stable version
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
  register: nginx_repo
  tags:
    - nginx

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: nginx_repo.changed
  tags:
    - nginx

- name: install
  apt: name=nginx state=latest update_cache=true cache_valid_time=3600
  tags: nginx

- name: remove conf.d/default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: reload-nginx
  tags: nginx

- name: remove sites-available/default
  file: path=/etc/nginx/sites-available/default state=absent
  notify: reload-nginx
  tags: nginx

- name: nginx - set nginx global config
  template:
    src: ../templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify: reload-nginx
  tags: nginx

- name: nginx - update mime types
  copy: src=etc/nginx/mime.types dest=/etc/nginx/mime.types owner=root group=root mode=0644
  notify: reload-nginx
  tags: nginx

- name: add corporeal api listener
  template: src=../templates/etc/nginx/conf.d/corporeal-api.conf dest=/etc/nginx/conf.d/corporeal-api.conf
  notify: reload-nginx
  tags:
    - nginx

- name: enable service
  service: name=nginx enabled=yes state=started
  tags: nginx
